/*
	SDZWsclassServiceExample.h
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import <Foundation/Foundation.h>

@interface SDZWsclassServiceExample : NSObject {
}
-(void)run;
@end
		