/*
	SDZWsclassServiceExample.m
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "SDZWsclassServiceExample.h"
#import "SDZWsclassService.h"

@implementation SDZWsclassServiceExample

- (void)run {
	// Create the service
	SDZWsclassService* service = [SDZWsclassService service];
	service.logging = YES;
	// service.username = @"username";
	// service.password = @"password";
	

	// Returns SDZOrderrWS*
	/*  */
	[service editOrderr:self action:@selector(editOrderrHandler:) email: @"" password: @"" id: @"" type: @"" hub: @"" patient: @"" cpo_name: @"" order_date: @"" recept_date: @"" cover: @"" model: @"" colour1: @"" colour2: @"" colour3: @"" amp_side: @"" top_calf: @"" max_calf: @"" mid_calf: @"" low_calf: @"" knee_ankle_axis: @""];

	// Returns SDZUserWS*
	/*  */
	[service editUser:self action:@selector(editUserHandler:) id: @"" password: @"" user: @"" clinic_name: @"" bill_street: @"" bill_city: @"" bill_country: @"" bill_zipcode: @"" bill_contact: @"" bill_phone: @"" ship_street: @"" ship_city: @"" ship_country: @"" ship_zipcode: @"" ship_contact: @"" ship_phone: @"" vat: @"" cpo_name: @"" cpo_email: @"" admin_name: @"" admin_email: @""];

	// Returns SDZArrayOfOrderr*
	/*  */
	[service getAllOrderr:self action:@selector(getAllOrderrHandler:) email: @"" password: @"" fechaUltComp: @""];

	// Returns SDZArrayOfOrderr*
	/*  */
	[service getAllOrderrByIduser:self action:@selector(getAllOrderrByIduserHandler:) email: @"" password: @"" fechaUltComp: @""];

	// Returns SDZOrderrWS*
	/*  */
	[service getOrderrById:self action:@selector(getOrderrByIdHandler:) email: @"" password: @"" idOrderr: @""];

	// Returns SDZUserWS*
	/*  */
	[service getUserById:self action:@selector(getUserByIdHandler:) email: @"" password: @"" idUser: @""];

	// Returns NSString*
	/*  */
	[service login:self action:@selector(loginHandler:) email: @"" password: @""];

	// Returns NSString*
	/* Datos necesarios para enviar notificacion
			 */
	[service registerDevice:self action:@selector(registerDeviceHandler:) email: @"" password: @"" deviceId: @"" sistema: @"" idioma: @"" version: @""];

	// Returns NSString*
	/*  */
	[service sendPhoto:self action:@selector(sendPhotoHandler:) email: @"" password: @"" idorder: @"" nombre: @"" image: @""];
}

	

// Handle the response from editOrderr.
		
- (void) editOrderrHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the SDZOrderrWS* result
		SDZOrderrWS* result = (SDZOrderrWS*)value;
	NSLog(@"editOrderr returned the value: %@", result);
			
}
	

// Handle the response from editUser.
		
- (void) editUserHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the SDZUserWS* result
		SDZUserWS* result = (SDZUserWS*)value;
	NSLog(@"editUser returned the value: %@", result);
			
}
	

// Handle the response from getAllOrderr.
		
- (void) getAllOrderrHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the SDZArrayOfOrderr* result
		SDZArrayOfOrderr* result = (SDZArrayOfOrderr*)value;
	NSLog(@"getAllOrderr returned the value: %@", result);
			
}
	

// Handle the response from getAllOrderrByIduser.
		
- (void) getAllOrderrByIduserHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the SDZArrayOfOrderr* result
		SDZArrayOfOrderr* result = (SDZArrayOfOrderr*)value;
	NSLog(@"getAllOrderrByIduser returned the value: %@", result);
			
}
	

// Handle the response from getOrderrById.
		
- (void) getOrderrByIdHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the SDZOrderrWS* result
		SDZOrderrWS* result = (SDZOrderrWS*)value;
	NSLog(@"getOrderrById returned the value: %@", result);
			
}
	

// Handle the response from getUserById.
		
- (void) getUserByIdHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the SDZUserWS* result
		SDZUserWS* result = (SDZUserWS*)value;
	NSLog(@"getUserById returned the value: %@", result);
			
}
	

// Handle the response from login.
		
- (void) loginHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"login returned the value: %@", result);
			
}
	

// Handle the response from registerDevice.
		
- (void) registerDeviceHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"registerDevice returned the value: %@", result);
			
}
	

// Handle the response from sendPhoto.
		
- (void) sendPhotoHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the NSString* result
		NSString* result = (NSString*)value;
	NSLog(@"sendPhoto returned the value: %@", result);
			
}
	

@end
		